server:
  port: 4200
  servlet:
    contextPath: /ext
  session:
    timeout: 1800
spring:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/learnit/
